### Load dataset

In [1]:
import pandas as pd
data = pd.read_csv("Loan and customer data.csv", nrows=200000)

C:\Users\hp\AppData\Local\Temp\ipykernel_11220\3456126520.py:2: DtypeWarning: Columns (19,59) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Loan and customer data.csv", nrows=200000)

### Exploratory data analysis, cleaning and proper formatting.

In [2]:
data.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=151)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Columns: 151 entries, id to settlement_term
dtypes: float64(114), int64(1), object(36)
memory usage: 230.4+ MB

In [4]:
data.shape

(200000, 151)

In [5]:
data.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.isnull().sum().sort_values(ascending=False).head(20)

sec_app_num_rev_accts                         200000
member_id                                     200000
revol_bal_joint                               200000
sec_app_fico_range_low                        200000
sec_app_fico_range_high                       200000
sec_app_earliest_cr_line                      200000
sec_app_inq_last_6mths                        200000
sec_app_mort_acc                              200000
sec_app_open_acc                              200000
sec_app_revol_util                            200000
sec_app_open_act_il                           200000
sec_app_chargeoff_within_12_mths              200000
sec_app_collections_12_mths_ex_med            200000
sec_app_mths_since_last_major_derog           200000
desc                                          199989
dti_joint                                     199491
annual_inc_joint                              199489
verification_status_joint                     199489
orig_projected_additional_accrued_interest    198873
hardship_length                               198591
dtype: int64

In [7]:
data["loan_status"].value_counts()

loan_status
Fully Paid            140992
Charged Off            35090
Current                22637
Late (31-120 days)       785
In Grace Period          347
Late (16-30 days)        148
Default                    1
Name: count, dtype: int64

Filter out the noise. Select columns that are relevant to business question.

In [8]:
selected_columns=["id", "loan_amnt", "term", "int_rate", "installment", "grade", 
                  "sub_grade", "emp_length", "home_ownership", "annual_inc", 
                  "verification_status", "purpose", "dti", "loan_status"]
df=data[selected_columns]

In [9]:
df.head(5)

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,loan_status
0,68407277,3600.0,36 months,13.99,123.03,C,C4,10+ years,MORTGAGE,55000.0,Not Verified,debt_consolidation,5.91,Fully Paid
1,68355089,24700.0,36 months,11.99,820.28,C,C1,10+ years,MORTGAGE,65000.0,Not Verified,small_business,16.06,Fully Paid
2,68341763,20000.0,60 months,10.78,432.66,B,B4,10+ years,MORTGAGE,63000.0,Not Verified,home_improvement,10.78,Fully Paid
3,66310712,35000.0,60 months,14.85,829.90,C,C5,10+ years,MORTGAGE,110000.0,Source Verified,debt_consolidation,17.06,Current
4,68476807,10400.0,60 months,22.45,289.91,F,F1,3 years,MORTGAGE,104433.0,Source Verified,major_purchase,25.37,Fully Paid

In [10]:
df.shape

(200000, 14)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   200000 non-null  int64
 1   loan_amnt            200000 non-null  float64
 2   term                 200000 non-null  object
 3   int_rate             200000 non-null  float64
 4   installment          200000 non-null  float64
 5   grade                200000 non-null  object
 6   sub_grade            200000 non-null  object
 7   emp_length           187897 non-null  object
 8   home_ownership       200000 non-null  object
 9   annual_inc           200000 non-null  float64
 10  verification_status  200000 non-null  object
 11  purpose              200000 non-null  object
 12  dti                  199998 non-null  float64
 13  loan_status          200000 non-null  object
dtypes: float64(5), int64(1), object(8)
memory usage: 21.4+ MB

In [12]:
df.isnull().sum().head(14)

id                         0
loan_amnt                  0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_length             12103
home_ownership             0
annual_inc                 0
verification_status        0
purpose                    0
dti                        2
loan_status                0
dtype: int64

In [13]:
df["emp_length"].value_counts(dropna=False)

emp_length
10+ years    67516
2 years      17529
< 1 year     16736
3 years      15851
1 year       13111
NaN          12103
5 years      11933
4 years      11449
8 years      10205
7 years       7893
9 years       7840
6 years       7834
Name: count, dtype: int64

In [14]:
df["emp_length"].unique()

array(['10+ years', '3 years', '4 years', '6 years', '1 year', '7 years',
       '8 years', '5 years', '2 years', '9 years', '< 1 year', nan],
      dtype=object)

In [15]:
df["term"].value_counts()

term
36 months    134643
60 months     65357
Name: count, dtype: int64

In [16]:
df["term"].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [17]:
df["term"]=df["term"].str.strip()

C:\Users\hp\AppData\Local\Temp\ipykernel_11220\830504145.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["term"]=df["term"].str.strip()

In [18]:
df["term"]=df["term"].str.replace(" months", "", regex=False)

C:\Users\hp\AppData\Local\Temp\ipykernel_11220\3557896420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["term"]=df["term"].str.replace(" months", "", regex=False)

In [19]:
df["term"]=df["term"].astype(int)

C:\Users\hp\AppData\Local\Temp\ipykernel_11220\1797106232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["term"]=df["term"].astype(int)

In [20]:
df=df.dropna(subset=["term"])

In [21]:
df["term"].isnull().sum()

np.int64(0)

In [22]:
df["emp_length"]=df["emp_length"].str.strip()

In [23]:
df["emp_length"]=df["emp_length"].str.replace("10+ years", "10", regex=False)
df["emp_length"]=df["emp_length"].str.replace("< 1 year", "1", regex=False)
df["emp_length"]=df["emp_length"].str.replace(" years", "", regex=False)
df["emp_length"]=df["emp_length"].str.replace(" year", "", regex=False)

In [24]:
df["emp_length"]=pd.to_numeric(df["emp_length"])

In [25]:
df["emp_length"].dtype

dtype('float64')

In [26]:
df.head(5)

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,loan_status
0,68407277,3600.0,36,13.99,123.03,C,C4,10.0,MORTGAGE,55000.0,Not Verified,debt_consolidation,5.91,Fully Paid
1,68355089,24700.0,36,11.99,820.28,C,C1,10.0,MORTGAGE,65000.0,Not Verified,small_business,16.06,Fully Paid
2,68341763,20000.0,60,10.78,432.66,B,B4,10.0,MORTGAGE,63000.0,Not Verified,home_improvement,10.78,Fully Paid
3,66310712,35000.0,60,14.85,829.90,C,C5,10.0,MORTGAGE,110000.0,Source Verified,debt_consolidation,17.06,Current
4,68476807,10400.0,60,22.45,289.91,F,F1,3.0,MORTGAGE,104433.0,Source Verified,major_purchase,25.37,Fully Paid

- Create our default flag and categorize for risk analysis.

In [27]:
df["loan_status"].unique()

array(['Fully Paid', 'Current', 'Charged Off', 'In Grace Period',
       'Late (31-120 days)', 'Late (16-30 days)', 'Default'], dtype=object)

In [28]:
def classify_risk(loan_status):
    if loan_status in ["Fully Paid", "Current"]:
        return "Performing loans"
    elif loan_status in ["In Grace Period", "Late (16-30 days)"]:
        return "Watchlist loans"
    elif loan_status in ["Late (31-120 days)"]:
        return "High risk loans"
    elif loan_status in ["Charged Off", "Default"]:
        return "Defaulted"
    else:
        return "Unknown"

In [29]:
df["risk_stage"]=df["loan_status"].apply(classify_risk)

In [30]:
df.head(5)

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,loan_status,risk_stage
0,68407277,3600.0,36,13.99,123.03,C,C4,10.0,MORTGAGE,55000.0,Not Verified,debt_consolidation,5.91,Fully Paid,Performing loans
1,68355089,24700.0,36,11.99,820.28,C,C1,10.0,MORTGAGE,65000.0,Not Verified,small_business,16.06,Fully Paid,Performing loans
2,68341763,20000.0,60,10.78,432.66,B,B4,10.0,MORTGAGE,63000.0,Not Verified,home_improvement,10.78,Fully Paid,Performing loans
3,66310712,35000.0,60,14.85,829.90,C,C5,10.0,MORTGAGE,110000.0,Source Verified,debt_consolidation,17.06,Current,Performing loans
4,68476807,10400.0,60,22.45,289.91,F,F1,3.0,MORTGAGE,104433.0,Source Verified,major_purchase,25.37,Fully Paid,Performing loans

In [31]:
df["risk_stage"].value_counts()

risk_stage
Performing loans    163629
Defaulted            35091
High risk loans        785
Watchlist loans        495
Name: count, dtype: int64

- Push dataset to MySQL for pipeline creation and future use.

In [32]:
export_df=df.copy()

In [33]:
export_df.shape

(200000, 15)

In [34]:
export_df.head(4)

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,loan_status,risk_stage
0,68407277,3600.0,36,13.99,123.03,C,C4,10.0,MORTGAGE,55000.0,Not Verified,debt_consolidation,5.91,Fully Paid,Performing loans
1,68355089,24700.0,36,11.99,820.28,C,C1,10.0,MORTGAGE,65000.0,Not Verified,small_business,16.06,Fully Paid,Performing loans
2,68341763,20000.0,60,10.78,432.66,B,B4,10.0,MORTGAGE,63000.0,Not Verified,home_improvement,10.78,Fully Paid,Performing loans
3,66310712,35000.0,60,14.85,829.90,C,C5,10.0,MORTGAGE,110000.0,Source Verified,debt_consolidation,17.06,Current,Performing loans

In [35]:
#pip install mysql-connector-python

In [36]:
import mysql.connector

conn=mysql.connector.connect(
    host="localhost",
    user="root",
    password="Kt212tiffanygraca#",
    database="loan_risk_analysis"
)
cursor=conn.cursor()

In [37]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS loans(
               id INT,
               loan_amnt FLOAT,
               term INT,
               int_rate FLOAT,
               installment FLOAT,
               grade VARCHAR(10),
               sub_grade VARCHAR(10),
               emp_length INT,
               home_ownership VARCHAR(50),
               annual_inc FLOAT,
               verification_status VARCHAR(50),
               purpose VARCHAR(100),
               dti FLOAT,
               loan_status VARCHAR(50),
               risk_stage VARCHAR(50)
)
""")

conn.commit()

In [38]:
insert_querry="""
INSERT INTO loans(
id, loan_amnt, term, int_rate, installment, grade, sub_grade, emp_length, home_ownership,
annual_inc, verification_status, purpose, dti, loan_status, risk_stage
)
VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) 
"""

data=list(export_df.itertuples(index=False, name=None))
cursor.executemany(insert_querry, data)
conn.commit()

- More analytical insights before we visualize for better understanding of risk

##### Distribution of risk

In [39]:
df["risk_stage"].value_counts()

risk_stage
Performing loans    163629
Defaulted            35091
High risk loans        785
Watchlist loans        495
Name: count, dtype: int64

In [40]:
df.groupby("risk_stage")["loan_status"].value_counts()

risk_stage        loan_status
Defaulted         Charged Off            35090
                  Default                    1
High risk loans   Late (31-120 days)       785
Performing loans  Fully Paid            140992
                  Current                22637
Watchlist loans   In Grace Period          347
                  Late (16-30 days)        148
Name: count, dtype: int64

In [41]:
df["risk_stage"].value_counts(normalize=True)*100

risk_stage
Performing loans    81.8145
Defaulted           17.5455
High risk loans      0.3925
Watchlist loans      0.2475
Name: proportion, dtype: float64

- We know the default is happening, question is, who is defaulting?

In [42]:
df["grade"].value_counts()

grade
B    59333
C    57429
A    34866
D    27863
E    15426
F     4192
G      891
Name: count, dtype: int64

In [43]:
df.groupby("grade")["risk_stage"].value_counts()

grade  risk_stage
A      Performing loans    33041
       Defaulted            1800
       High risk loans        17
       Watchlist loans         8
B      Performing loans    52261
       Defaulted            6876
       High risk loans       131
       Watchlist loans        65
C      Performing loans    45790
       Defaulted           11197
       High risk loans       262
       Watchlist loans       180
D      Performing loans    19894
       Defaulted            7667
       High risk loans       173
       Watchlist loans       129
E      Performing loans     9878
       Defaulted            5314
       High risk loans       148
       Watchlist loans        86
F      Performing loans     2337
       Defaulted            1788
       High risk loans        43
       Watchlist loans        24
G      Defaulted             449
       Performing loans      428
       High risk loans        11
       Watchlist loans         3
Name: count, dtype: int64

In [44]:
pd.crosstab(
    df["grade"],
    df["risk_stage"],
    normalize=True
)*100

risk_stage  Defaulted  High risk loans  Performing loans  Watchlist loans
grade
A              0.9000           0.0085           16.5205           0.0040
B              3.4380           0.0655           26.1305           0.0325
C              5.5985           0.1310           22.8950           0.0900
D              3.8335           0.0865            9.9470           0.0645
E              2.6570           0.0740            4.9390           0.0430
F              0.8940           0.0215            1.1685           0.0120
G              0.2245           0.0055            0.2140           0.0015

In [45]:
df.groupby("risk_stage")["int_rate"].mean()

risk_stage
Defaulted           14.730097
High risk loans     15.320854
Performing loans    11.830553
Watchlist loans     15.374465
Name: int_rate, dtype: float64

In [46]:
df.groupby("risk_stage")["loan_amnt"].mean()

risk_stage
Defaulted           15772.701690
High risk loans     19607.611465
Performing loans    15136.016537
Watchlist loans     20339.494949
Name: loan_amnt, dtype: float64

##### Borrower's behavior

In [47]:
df.groupby("emp_length")["risk_stage"].value_counts()

emp_length  risk_stage
1.0         Performing loans    24228
            Defaulted            5439
            High risk loans       115
            Watchlist loans        65
2.0         Performing loans    14394
            Defaulted            3011
            High risk loans        85
            Watchlist loans        39
3.0         Performing loans    12973
            Defaulted            2778
            High risk loans        64
            Watchlist loans        36
4.0         Performing loans     9326
            Defaulted            2043
            High risk loans        51
            Watchlist loans        29
5.0         Performing loans     9721
            Defaulted            2138
            High risk loans        44
            Watchlist loans        30
6.0         Performing loans     6423
            Defaulted            1349
            High risk loans        39
            Watchlist loans        23
7.0         Performing loans     6494
            Defaulted            1351
            High risk loans        31
            Watchlist loans        17
8.0         Performing loans     8333
            Defaulted            1811
            High risk loans        37
            Watchlist loans        24
9.0         Performing loans     6385
            Defaulted            1412
            High risk loans        25
            Watchlist loans        18
10.0        Performing loans    56080
            Defaulted           10977
            High risk loans       257
            Watchlist loans       202
Name: count, dtype: int64

In [48]:
df.groupby("emp_length")["risk_stage"].apply(
    lambda x:(x=="Defaulted").mean()*100
)

emp_length
1.0     18.222937
2.0     17.177249
3.0     17.525708
4.0     17.844353
5.0     17.916702
6.0     17.219811
7.0     17.116432
8.0     17.746203
9.0     18.010204
10.0    16.258368
Name: risk_stage, dtype: float64

##### Behavioral intent

In [49]:
df.groupby("purpose")["risk_stage"].value_counts()

purpose             risk_stage
car                 Performing loans     1442
                    Defaulted             241
                    High risk loans         8
                    Watchlist loans         3
credit_card         Performing loans    43177
                    Defaulted            7346
                    High risk loans       177
                    Watchlist loans       117
debt_consolidation  Performing loans    92354
                    Defaulted           21601
                    High risk loans       483
                    Watchlist loans       312
home_improvement    Performing loans    10528
                    Defaulted            1992
                    High risk loans        48
                    Watchlist loans        31
house               Performing loans      492
                    Defaulted             159
                    Watchlist loans         4
                    High risk loans         3
major_purchase      Performing loans     3169
                    Defaulted             652
                    High risk loans        16
                    Watchlist loans         9
medical             Performing loans     1670
                    Defaulted             406
                    High risk loans         6
                    Watchlist loans         4
moving              Performing loans      875
                    Defaulted             239
                    High risk loans         1
other               Performing loans     7807
                    Defaulted            1814
                    High risk loans        26
                    Watchlist loans        11
renewable_energy    Performing loans       82
                    Defaulted              30
small_business      Performing loans     1199
                    Defaulted             433
                    High risk loans        15
                    Watchlist loans         3
vacation            Performing loans      833
                    Defaulted             178
                    High risk loans         2
                    Watchlist loans         1
wedding             Performing loans        1
Name: count, dtype: int64

In [50]:
df.groupby("purpose")["risk_stage"].apply(
    lambda x: (x=="Defaulted").mean()*100
).sort_values(ascending=False)

purpose
renewable_energy      26.785714
small_business        26.242424
house                 24.164134
moving                21.434978
medical               19.463087
debt_consolidation    18.824401
other                 18.782357
vacation              17.554241
major_purchase        16.952678
home_improvement      15.810779
credit_card           14.455792
car                   14.226682
wedding                0.000000
Name: risk_stage, dtype: float64

##### Feature Interaction

In [51]:
df.groupby("purpose")["int_rate"].mean().sort_values(ascending=False)

purpose
house                 16.695653
small_business        16.309248
renewable_energy      15.366518
moving                15.019883
other                 13.877449
medical               13.488188
wedding               13.330000
vacation              13.274586
debt_consolidation    12.816994
major_purchase        12.159724
home_improvement      12.133610
car                   11.658619
credit_card           10.827328
Name: int_rate, dtype: float64

##### Interraction analysis

In [52]:
df["loan_amt_band"] = pd.qcut(df["loan_amnt"], 4, labels=["Low", "Mid", "High", "Very High"])
df.groupby(["loan_amt_band", "risk_stage"])["int_rate"].mean()

C:\Users\hp\AppData\Local\Temp\ipykernel_11220\2797135734.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["loan_amt_band", "risk_stage"])["int_rate"].mean()

loan_amt_band  risk_stage
Low            Defaulted           13.389935
               High risk loans     12.095882
               Performing loans    11.348300
               Watchlist loans     17.595000
Mid            Defaulted           14.476679
               High risk loans     15.242574
               Performing loans    11.574471
               Watchlist loans     15.257913
High           Defaulted           14.830412
               High risk loans     15.273834
               Performing loans    11.789966
               Watchlist loans     14.906524
Very High      Defaulted           16.020939
               High risk loans     15.584537
               Performing loans    12.653580
               Watchlist loans     15.774953
Name: int_rate, dtype: float64

##### Dashboard preparation

In [53]:
risk_summary = df.groupby("risk_stage").agg(
    total_loans=("id", "count"),
    avg_loan_amount=("loan_amnt", "mean"),
    avg_interest_rate=("int_rate", "mean"),
    avg_income=("annual_inc", "mean")
).reset_index()

risk_summary

,risk_stage,total_loans,avg_loan_amount,avg_interest_rate,avg_income
0,Defaulted,35091,15772.701690,14.730097,70851.175247
1,High risk loans,785,19607.611465,15.320854,79599.371096
2,Performing loans,163629,15136.016537,11.830553,79687.038662
3,Watchlist loans,495,20339.494949,15.374465,85508.196384

In [54]:
risk_summary=risk_summary.round(2)

###### Save and pull the loans table to Power BI for visual analysis

In [55]:
df.to_excel("loan_fact_table.xlsx", index=False)